### PR TITLE
Convert to Go modules

### PR DESCRIPTION
**Pull request by SuperQ**
Replace govendor with Go modules.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by josephlewis42** [comment]
there's an issue with go 1.13 and modules, looks like you got it though

**Comment by SuperQ** [comment]
Yea, there will be some more work to get the vendoring and code up to date to work with Go 1.13 I think. Wanted to do this incrementally.

**Comment by SuperQ** [comment]
I added a commit to drop the `/vendor` dir, which isn't as necessary with Go modules.

**Comment by josephlewis42** [comment]
here's a working travis from a gomod project for reference: https://github.com/google/kf/blob/develop/.travis.yml

**Comment by josephlewis42** [comment]
I think by including the `go_import_path` go will revert back to non module status unless you force it on with an env var

**Comment by SuperQ** [comment]
Ahh, possibly, I'll try removing that.

**Comment by SuperQ** [comment]
We jump through a lot of hoops in our Makefile[0] to get Go modules to do what we want. :smirk_cat:
[0]: https://github.com/prometheus/prometheus/blob/master/Makefile.common

**Comment by SuperQ** [comment]
It looks like the real problem with 1.13 is that go mod changed the real dependency on some code. Will see if I can sort that out.

**Comment by josephlewis42** [comment]
it's insane that a beat is pulling in k8s watchers

**Comment by SuperQ** [comment]
I think a whole bunch of the issues here is that there were updates to the /vendor directory that didn't update the vendor.json file. I'm still trying to un-tangle the modules dependencies to get it to build locally.

**Comment by josephlewis42** [comment]
I can poke at this tomorrow as well. I don't mind doing the toil-y work if it gets you unblocked for a #26 solution you'll be happy with

**Comment by SuperQ** [comment]
Ok, there's still a bunch of vendor code that needs updating and migrations. But this should be an improvement.

**Comment by SuperQ** [comment]
When I add Go 1.13.x, I am getting a test panic.

It seems to be related to main_test.go:
```
	cmd.RootCmd.PersistentFlags().AddGoFlag(flag.CommandLine.Lookup("test.coverprofile"))
```

```
$ make test
go test ./...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d5b5d6]
goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddGoFlag(0xc00050ce00, 0x0)
	/home/travis/gopath/pkg/mod/github.com/spf13/pflag@v1.0.5/golangflag.go:86 +0x26
github.com/GoogleCloudPlatform/pubsubbeat.init.0()
	/home/travis/gopath/src/github.com/GoogleCloudPlatform/pubsubbeat/main_test.go:32 +0x151
FAIL	github.com/GoogleCloudPlatform/pubsubbeat	0.041s
?   	github.com/GoogleCloudPlatform/pubsubbeat/beater	[no test files]
?   	github.com/GoogleCloudPlatform/pubsubbeat/cmd	[no test files]
ok  	github.com/GoogleCloudPlatform/pubsubbeat/config	0.007s
FAIL
Makefile:17: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by SuperQ** [comment]
Yea, that seems like a reasonable workaround. Added.

**Comment by josephlewis42** [comment]
@SuperQ is this good to go then?

**Comment by SuperQ** [comment]
After the cleanup, I was able to bump all the go module vendoring to latest, so we're fresh n clean for all dependencies.

Should be good to go as soon as tests pass.

**Comment by josephlewis42** [comment]
Awesome work @SuperQ thanks!

**Pull request merged**
