### PR TITLE
Support typeless mapping

### LINKED ISSUE #23: Support for typeless mapping in ES7
### Background
In ES7, [types got removed](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types). 

### Issue
Currently, the pubsubbeat adds a mapping type regardless of the ES version. (To be specific: It adds a `doc` mapping type for ES6 or above and a `_default_` for everything below). Users are not able to get the current pubsubbeat working with ES7 because ES7 no longer allows mapping types. A sample error is:

```
ERROR pipeline/output.go:74 Failed to connect: Connection marked as failed because the onConnect callback failed: Error loading Elasticsearch template: could not load template: couldn't load template: couldn't load json. Error: 400 Bad Request: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters: [doc : {_meta={version=6.2.2}, dynamic_templates=[{fields={path_match=fields.*, mapping={type=keyword}, match_mapping_type=string}}, {docker.container.labels={path_match=docker.container.labels.*, mapping={type=keyword}, match_mapping_type=string}}, {fields={path_match=fields.*, mapping={type=keyword}, match_mapping_type=string}}, {docker.container.labels={path_match=docker.container.labels.*, mapping={type=keyword}, match_mapping_type=string}}, {strings_as_keyword={mapping={ignore_above=1024, type=keyword}, match_mapping_type=string}}], properties={kubernetes={properties={container={properties={image={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}}}, node={properties={name={ignore_above=1024, type=keyword}}}, pod={properties={name={ignore_above=1024, type=keyword}}}, namespace={ignore_above=1024, type=keyword}, annotations={type=object}, labels={type=object}}}, message_id={norms=false, type=text}, error={properties={code={type=long}, type={ignore_above=1024, type=keyword}, message={norms=false, type=text}}}, message={norms=false, type=text}, tags={ignore_above=1024, type=keyword}, docker={properties={container={properties={image={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, labels={type=object}}}}}, @timestamp={type=date}, meta={properties={cloud={properties={machine_type={ignore_above=1024, type=keyword}, availability_zone={ignore_above=1024, type=keyword}, instance_id={ignore_above=1024, type=keyword}, instance_name={ignore_above=1024, type=keyword}, project_id={ignore_above=1024, type=keyword}, provider={ignore_above=1024, type=keyword}, region={ignore_above=1024, type=keyword}}}}}, publish_time={type=date}, beat={properties={hostname={ignore_above=1024, type=keyword}, timezone={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}}}, json={type=object}, attributes={type=object}, fields={type=object}}, date_detection=false}]"}]
```

### Proposal 
Make change so that no mapping type is provided if ES version is >= 7 and make corresponding changes that are required for it (references...etc). I plan to send a PR for it but wanted to capture the background and thought process here following the contribution guideline. (As of writing this, Github is down... so once they recover...)

### PR DESCRIPTION
**Pull request by amarbayar**
Added support for ES7 - Typeless Mapping. Closes #23

### CODE REVIEW

**Comment by amarbayar** [comment]
Added work email to my settings - to see if it works.

**Comment by ScubaDrew** [comment]
@amarbayar Any hope of you continuing this?

**Comment by ScubaDrew** [comment]
@josephlewis42 This would be really nice to have. The new versions of ES are very good but this blocks us from using them.

**Comment by josephlewis42** [comment]
I think this is fixed as of the move to go modules. Closing unless we find that's not the case.

**Pull request closed without merging**
